# Generated by Django 4.2.7 on 2024-03-14 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель')),
                ('launch_date', models.DateField(verbose_name='Дата старта продаж')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='SupplyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('category', models.CharField(choices=[('FCT', 'Factory'), ('RET', 'Retail'), ('ENT', 'Entrepreneur')], max_length=3, verbose_name='Категория')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Задолженность')),
                ('tier', models.PositiveSmallIntegerField(default=0, verbose_name='Уровень поставщика')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('products', models.ManyToManyField(to='main.product', verbose_name='Товары')),
                ('supplier_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.supplynode', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Торговое звено',
                'verbose_name_plural': 'Торговые звенья',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица')),
                ('building_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер дома')),
                ('supply_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supplynode', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
